name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Turnstyle
      if: ${{ github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Image
      run: docker build --tag meat:latest .
    
    - name: Push to GitHub
      if: ${{ github.repository == 'scrotegang/meat' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag meat:latest ghcr.io/scrotegang/meat:latest
        docker push ghcr.io/scrotegang/meat:latest
